In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("cleaned_all_phones.csv")

In [30]:
df

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
0,Y6II Compact,Huawei,Android 5.1,5.00,720x1280,2200,Li-Po,2,2016-09-01,140.0,...,False,False,False,True,False,False,False,False,False,120.000
1,K20 plus,LG,Android 7.0,5.30,720x1280,2700,Li-Ion,2,2016-12-01,140.0,...,True,False,False,True,False,False,False,False,False,100.000
2,P8 Lite (2017),Huawei,Android 7.0,5.20,1080x1920,3000,Li-Ion,4,2017-01-01,147.0,...,True,False,False,True,False,False,False,False,False,420.000
3,Redmi Note 4,Xiaomi,Android 6.0,5.50,1080x1920,4100,Li-Po,4,2017-01-01,165.0,...,True,False,False,True,False,True,False,False,False,150.000
4,P10,Huawei,Android 7.0,5.10,1080x1920,3200,Li-Ion,4,2017-02-01,145.0,...,True,True,False,True,True,False,False,False,False,420.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,vivo Y77t,Vivo,Android 13,6.64,1080x2388,5000,Li-Po,8,2023-08-18,190.0,...,True,False,False,True,False,False,False,False,False,170.000
1508,11x,Realme,Android 13,6.72,1080x2400,5000,Li-Po,8,2023-08-23,190.0,...,True,False,False,True,False,False,False,False,False,182.880
1509,GT5,Realme,Android 13,6.74,1240x2772,5240,Li-Po,16,2023-08-28,205.0,...,True,True,False,False,True,False,False,False,False,380.000
1510,GT5 240W,Realme,Android 13,6.74,1240x2772,4600,Li-Po,24,2023-08-28,205.0,...,True,True,False,False,True,False,False,False,False,470.000
1511,vivo iQOO Z7 Pro,Vivo,Android 13,6.78,1080x2400,4600,Li-Po,8,2023-08-31,175.0,...,True,True,False,True,False,False,False,False,False,287.988

# 1
Rata-rata

In [31]:
rata_rata = np.mean(df)
rata_rata

/Users/dimasgusti/Library/Python/3.9/lib/python/site-packages/numpy/core/fromnumeric.py:3438: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/Users/dimasgusti/Library/Python/3.9/lib/python/site-packages/numpy/core/fromnumeric.py:3438: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

inches             6.422460
battery         4389.798942
ram(GB)            6.683862
weight(g)        187.636243
storage(GB)      109.164683
video_720p         0.539683
video_1080p        0.994048
video_4K           0.529762
video_8K           0.056878
video_30fps        0.891534
video_60fps        0.374339
video_120fps       0.271164
video_240fps       0.133598
video_480fps       0.023148
video_960fps       0.146825
price(USD)       337.847036
dtype: float64

Standar Deviasi

In [32]:
deviasi = df['price(USD)'].std()
deviasi

266.74082133237664

Nilai Min

In [33]:
min = df['price(USD)'].min()
min

40.0

Nilai Max

In [34]:
max = df['price(USD)'].max()
max

2300.0

Kuartil 1

In [35]:
q1 = df['price(USD)'].quantile(0.25)
q1

179.9975

Kuartil 2

In [36]:
q2 = df['price(USD)'].median()
q2

260.0

Kuartil 3

In [37]:
q3 = df['price(USD)'].quantile(0.75)
q3

400.0

# 2
10 Record pertama

In [38]:
df_numeric = df.select_dtypes(include=[np.number])
df_numeric.head(10)

   inches  battery  ram(GB)  weight(g)  storage(GB)  price(USD)
0     5.0     2200        2      140.0           16       120.0
1     5.3     2700        2      140.0           16       100.0
2     5.2     3000        4      147.0           16       420.0
3     5.5     4100        4      165.0           32       150.0
4     5.1     3200        4      145.0           32       420.0
5     5.0     2300        3      143.0           32       140.0
6     5.2     3000        4      146.0           32       420.0
7     5.5     3750        6      165.0           64       170.0
8     6.0     2700        4      188.0           32       250.0
9     5.5     4500        2      164.0           16       170.0

Informasi

In [39]:
info_dict = {
    'Jumlah Record': len(df),
    'Jumlah Attribute': len(df.columns),
    'Nama Attribute': df.columns.tolist(),
    'Jumlah Attribut dengan Tipe Angka': len(df.select_dtypes(include=[np.number]).columns)
}
info_dict

{'Jumlah Record': 1512,
 'Jumlah Attribute': 22,
 'Nama Attribute': ['phone_name',
  'brand',
  'os',
  'inches',
  'resolution',
  'battery',
  'battery_type',
  'ram(GB)',
  'announcement_date',
  'weight(g)',
  'storage(GB)',
  'video_720p',
  'video_1080p',
  'video_4K',
  'video_8K',
  'video_30fps',
  'video_60fps',
  'video_120fps',
  'video_240fps',
  'video_480fps',
  'video_960fps',
  'price(USD)'],
 'Jumlah Attribut dengan Tipe Angka': 6}

Nilai dataset pada baris dimulai dengan NIM 124 - data terakhir, kolom 4 - akhir dengan slice

In [42]:
data_slice_1 = df.iloc[:, 3:]
data_slice_1

# data_slice_2 = df.loc[df['124'] == 'XXX' , df.columns[3:]]
# data_slice_2

,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),storage(GB),video_720p,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
0,5.00,720x1280,2200,Li-Po,2,2016-09-01,140.0,16,True,False,False,False,True,False,False,False,False,False,120.000
1,5.30,720x1280,2700,Li-Ion,2,2016-12-01,140.0,16,False,True,False,False,True,False,False,False,False,False,100.000
2,5.20,1080x1920,3000,Li-Ion,4,2017-01-01,147.0,16,False,True,False,False,True,False,False,False,False,False,420.000
3,5.50,1080x1920,4100,Li-Po,4,2017-01-01,165.0,32,True,True,False,False,True,False,True,False,False,False,150.000
4,5.10,1080x1920,3200,Li-Ion,4,2017-02-01,145.0,32,True,True,True,False,True,True,False,False,False,False,420.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,6.64,1080x2388,5000,Li-Po,8,2023-08-18,190.0,256,False,True,False,False,True,False,False,False,False,False,170.000
1508,6.72,1080x2400,5000,Li-Po,8,2023-08-23,190.0,128,False,True,False,False,True,False,False,False,False,False,182.880
1509,6.74,1240x2772,5240,Li-Po,16,2023-08-28,205.0,256,True,True,True,False,False,True,False,False,False,False,380.000
1510,6.74,1240x2772,4600,Li-Po,24,2023-08-28,205.0,1,True,True,True,False,False,True,False,False,False,False,470.000
1511,6.78,1080x2400,4600,Li-Po,8,2023-08-31,175.0,128,True,True,True,False,True,False,False,False,False,False,287.988

Tampilkan jumlah label dari semua attribute yang bernilai object

In [43]:
label_count = df.select_dtypes(include=['object']).nunique()
label_count

phone_name           1496
brand                  13
os                     34
resolution             85
battery_type            2
announcement_date     665
dtype: int64